### ISSUE TITLE
all channels except digi24 don't work !

### ISSUE THREAD

**Issue by maurerr** [dexterke/plugin.video.digi-online#5]
all channels except digi24 don't work !
Can you take a look?

thanks

**Comment by dexterke** [comment]
Have you tried to access http://www.digi-online.ro/ ? The plugin is only a wrapper tool for the live channels available there, programmes that you can access from your browser would (with a very few exceptions) work from Kodi as well. 

Updated DIsclaimer:

The author does not host or own any content found within this Addon. The author is not connected to or in any other way affiliated with Kodi, Team Kodi, the XBMC foundation, RCS RDS SA, digi24.ro or digi-online.ro Due to copyright and licensing reasons beyond the author's control, access to Digi-Online TV programmes may be subject to geoblocking (access restricted for viewers outside RCS-RDS Romania network).

**Comment by maurerr** [comment]
you're right - i had to remove the other devices from my digi account
thanks !!!
